platform :ios,'7.0'

target 'JQDemoProgram' do
        
    # 网络访问
    pod 'AFNetworking', '~>2.0'
    # 网络图片加载、缓存
    pod 'SDWebImage', '~>3.7'
    # 悬浮提示框
    pod 'MBProgressHUD', '~> 0.9.1'

    # UMeng组件
    pod 'UMengFeedback', '~> 2.3.4'
    pod 'UMengAnalytics'

    # 具有底层按钮的tableviewcell
    pod 'SWTableViewCell', '~> 0.3.7'

    # CoreData支持
    pod 'MagicalRecord'
    
    pod 'JSPatch', '~> 0.2'

end