platform :ios,'7.0'
# 网络访问
pod 'AFNetworking', '~>2.0'
# 网络图片加载、缓存
pod 'SDWebImage', '~>3.7'
# 悬浮提示框
pod 'MBProgressHUD', '~> 0.9.1'

# UMeng组件
pod 'UMengFeedback', '~> 2.3.4'
# 具有底层按钮的tableviewcell
pod 'SWTableViewCell', '~> 0.3.7'



